#[macro_use]
extern crate rocket;

use rocket::http::Status;
use rocket::serde::{json::Json, Deserialize, Serialize};

// 1. CORRECT IMPORTS
// We removed 'Database'. We only need 'database' (the macro) and 'diesel' (the module).
use rocket_sync_db_pools::{database, diesel}; 

// We import standard diesel prelude for query helpers (insert_into, etc)
use diesel::prelude::*;

mod schema;

// 2. DATABASE CONFIGURATION
// We use the diesel module from inside rocket_sync_db_pools to guarantee version compatibility.
#[database("my_db")]
struct Db(rocket_sync_db_pools::diesel::PgConnection);

// 3. MODELS
#[derive(Debug, Deserialize, Serialize)]
#[serde(crate = "rocket::serde")]
struct UserProfile {
    email: String,
    age: i32,
}

#[derive(Insertable)]
#[diesel(table_name = schema::users)]
struct NewUser {
    email: String,
    age: i32,
}

// 4. ROUTES
#[post("/register", format = "json", data = "<profile>")]
async fn register(conn: Db, profile: Json<UserProfile>) -> Result<String, (Status, String)> {
    let new_user = NewUser {
        email: profile.email.clone(),
        age: profile.age,
    };

    // conn.run() moves the blocking database work to a background thread
    let result = conn.run(move |c| {
        diesel::insert_into(schema::users::table)
            .values(&new_user)
            .execute(c)
    }).await;

    match result {
        Ok(_) => Ok(format!("Success! Registered: {}", profile.email)),
        Err(e) => Err((Status::InternalServerError, e.to_string())),
    }
}

#[get("/")]
fn home() -> &'static str {
    "Server is running!"
}

// 5. LAUNCH
#[launch]
fn rocket() -> _ {
    rocket::build()
        // The .init() method is generated by the #[database] macro above.
        // It should work now that the imports are clean.
        .attach(Db::init()) 
        .mount("/", routes![home, register])
}